import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

import {
  classifyRelease,
  isPreRelease,
  type ReleaseKind,
} from "../src/data/release-kind.ts";

const cases: [tag: string, name: string, kind: ReleaseKind][] = [
  // Stable versions, including short tags and named releases.
  ["v1.6.1", "v1.6.1", "stable"],
  ["v0.11", "v0.11", "stable"],
  ["v1.0.0", "TypeWhisper 1.0", "stable"],
  ["v0.7.0", "v0.7.0 - Notch Indicator", "stable"],
  ["1.2.3", "1.2.3", "stable"],
  // The tag decides: a plain version stays stable whatever the name says.
  ["v1.2.0", "v1.2.0 - Live preview", "stable"],
  // Daily builds of both desktop editions.
  ["v1.7.0-daily.20260922", "v1.7.0-daily.20260922", "daily"],
  ["v1.7.0-daily.20260909.1", "v1.7.0-daily.20260909.1", "daily"],
  [
    "v1.1.0-daily.20260923.48",
    "TypeWhisper v1.1.0-daily.20260923.48 · Daily",
    "daily",
  ],
  [
    "v1.1.0-daily.20260910.6",
    "TypeWhisper v1.1.0-daily.20260910.6 — Daily",
    "daily",
  ],
  ["v2.0.0-nightly.20270101", "v2.0.0-nightly.20270101", "daily"],
  // Release candidates and betas.
  ["v1.7.0-rc1", "v1.7.0-rc1", "candidate"],
  ["v1.0.0-rc2", "v1.0.0-rc2", "candidate"],
  ["v1.8.0-rc.3", "v1.8.0-rc.3", "candidate"],
  ["v2.0.0-beta.1", "v2.0.0-beta.1", "candidate"],
  ["v2.0.0-alpha", "v2.0.0-alpha", "candidate"],
  ["v2.0.0-preview2", "v2.0.0-preview2", "candidate"],
  // An unknown suffix behind a version is never stable.
  ["v2.0.0-hotfix.1", "v2.0.0-hotfix.1", "candidate"],
  // Plugin releases, whatever their name mentions.
  [
    "plugins-winui-20260923",
    "TypeWhisper Plugins — Windows Daily, 23 September 2026",
    "plugin",
  ],
  [
    "plugins-v2-cloudflare-asr-1.1.7-20260918",
    "Cloudflare Workers AI 1.1.7 — V2 preview",
    "plugin",
  ],
  [
    "plugins-v2-deepgram-1.1.3-20260910",
    "Windows 1.1: Deepgram language selection fix",
    "plugin",
  ],
  [
    "plugins-v2-preview-20260908",
    "Windows 1.1 portable plugins — preview",
    "plugin",
  ],
  // Tags that are no version: the name decides.
  ["build-20270101", "Daily build, 1 January 2027", "daily"],
  ["latest", "Release Candidate for 2.0", "candidate"],
  ["latest", "TypeWhisper 2.0", "stable"],
];

for (const [tag_name, name, kind] of cases) {
  test(`${tag_name} (${name}) is ${kind}`, () => {
    assert.equal(classifyRelease({ tag_name, name }), kind);
    assert.equal(isPreRelease({ tag_name, name }), kind !== "stable");
  });
}

test("words that only contain a marker do not count", () => {
  assert.equal(
    classifyRelease({ tag_name: "v1.0.0-dailyish", name: "" }),
    "candidate",
  );
  assert.equal(
    classifyRelease({ tag_name: "release", name: "Prerecorded audio" }),
    "stable",
  );
});

test("a missing name is tolerated", () => {
  assert.equal(classifyRelease({ tag_name: "v1.0.0", name: null }), "stable");
  assert.equal(classifyRelease({ tag_name: "v1.0.0-rc1" }), "candidate");
});

// The feed is generated by `npm run dev` and `npm run build`; a fresh checkout
// has none yet, so the check only runs where the file exists.
const releaseFeed = new URL("../src/data/releases.json", import.meta.url);

test(
  "the generated feed holds no stable entry with a pre-release tag",
  {
    skip: existsSync(releaseFeed) ? false : "no generated release feed",
  },
  () => {
    const releases = JSON.parse(readFileSync(releaseFeed, "utf8")) as {
      tag_name: string;
      name: string;
    }[];
    const kinds = new Set<ReleaseKind>([
      "stable",
      "daily",
      "candidate",
      "plugin",
    ]);

    for (const release of releases) {
      const kind = classifyRelease(release);
      assert.ok(kinds.has(kind), `${release.tag_name}: unknown kind ${kind}`);
      if (kind === "stable") {
        assert.doesNotMatch(
          release.tag_name,
          /daily|nightly|-rc|beta|alpha|^plugins?-/i,
          `${release.tag_name} must not be listed as stable`,
        );
      }
    }
  },
);
